# Algorithimic complexity 
# Efficiency in programming-->Time->Space
# Time efficient - google search engine 

# for space efficieny 
# asphalt-8 and asphalt lite for space optimization 


# TC
# 1 Measuring time 

# for loop
import time
start = time.time()
for i in range(1,101):
    print(i)
print(time.time()-start)


# while loop
import time
start = time.time()
i=1
while i <101:
    print(i)
    i+=1
print(time.time()-start)


  
#List-List is a built-in dynamic array which can store elements of different data types. 
#It is an ordered collection of item, that is elements are stored in the same order as they were inserted into the list. 
#List stores references to the objects (elements) rather than storing the actual data itself.



